# Webhook listening port
port: 8080
# Number of alerts the webhook queue can contains while waiting for processing
queueCapacity: 500

# Hostname of your zabbix server
zabbixServerHost: zabbix-server-here
# Trapper port of your zabbix server
zabbixServerPort: 10051
# Look in this annotation for a zabbix host to send alerts to, if not present alert is ignored
zabbixHostAnnotation: instance
# Items key prefix, keys will be zabbixKeyPrefix.alertname
zabbixKeyPrefix: dev
